### ISSUE TITLE
Getting Error: 'base_template' on otterdog import

### ISSUE THREAD

**Issue by cunla** [eclipse-csi/otterdog#247]
```
> otterdog import {org} -vvv
Traceback (most recent call last):
  File "/home/style/.local/pipx/venvs/otterdog/lib/python3.10/site-packages/otterdog/cli.py", line 110, in invoke
    _CONFIG = OtterdogConfig.from_file(config_file, local_mode)
  File "/home/style/.local/pipx/venvs/otterdog/lib/python3.10/site-packages/otterdog/config.py", line 302, in from_file
    return cls(config_file, local_mode)
  File "/home/style/.local/pipx/venvs/otterdog/lib/python3.10/site-packages/otterdog/config.py", line 164, in __init__
    org_config = OrganizationConfig.from_dict(org, self)
  File "/home/style/.local/pipx/venvs/otterdog/lib/python3.10/site-packages/otterdog/config.py", line 89, in from_dict
    base_template = data.get("base_template", otterdog_config.default_base_template)
  File "/home/style/.local/pipx/venvs/otterdog/lib/python3.10/site-packages/otterdog/config.py", line 191, in default_base_template
    return self._jsonnet_config["base_template"]
KeyError: 'base_template'
╷
│ Error: 'base_template'
```

**Comment by cunla** [comment]
solved by adding this to config file:
```
  "defaults":{
    "jsonnet": {
      "base_template": "https://github.com/EclipseFdn/otterdog-defaults#otterdog-defaults.libsonnet@main",
      "config_dir": "orgs"
    }
  },
```

**Comment by netomi** [comment]
thanks for testing this out. That should have thrown an error indicating the problem instead of a stacktrace.

will change that accordingly. I assume there are other cases where mandatory settings are not properly checked in advance, as in our operational setup things are already defined. But if other people wanna use it as well they ofc run into such issues.

ty for checking it out.
